### ISSUE TITLE
Migrace jinam?

### ISSUE THREAD

**Issue by frenzymadness** [PyLadiesCZ/Zpetnovazebnik#50]
Doneslo se ke mě, že free Heroku končí. Je v plánu tuto aplikaci migrovat jinam?

**Comment by encukou** [comment]
Jo, je o tom thread na Slacku.

**Comment by encukou** [comment]
Hotovo! Kurzy, komentáře, uživatelské účty i hesla jsou zmigrované na https://zpetnovazebnik.pyladies.cz.
Aktualizujte si záložky, až to Heroku zařízne tak staré URL přestane fungovat.
